name: Hello World!

on:
    push:
        branches:
            - main

jobs:
    hello_world_job:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello
              run: |
                echo "Hello World!"
    prints_datetime:
        runs-on: ubuntu-latest
        steps:
            - name: Prints Current Datetime
              run: |
                 date

    list_dir:
        runs-on: ubuntu-latest
        steps:
            - name: List directory contents
              run: |
                ls -la
